メインページにファイル作成ボタンとファイル一覧ボタンを作成
yuuki-foll/Pylon pull request #24
Opened 2022-11-29 15:57 UTC by yuji-matsunami

## やったこと

* このプルリクで何をしたのか？
  * #15 の対応になります 
  * ファイル作成ボタンと、ファイル一覧表示ボタンを追加
  * 二つのボタンとも認証が済んでいない場合は、先に認証ページにリダイレクトされます。

## やらないこと

* このプルリクでやらないことは何か？（あれば。無いなら「無し」でOK）（やらない場合は、いつやるのかを明記する。）
  * ボタンのデザイン、ボタンの表示している文字は仮で入れてます。
    * 何か要望があればレビューに記載お願いします。 

## 動作確認

* どのような動作確認を行ったのか？　結果はどうか？
  - 認証せずにpylonに移動し、二つのボタンを押して動作確認しました。
![スクリーンショット 2022-11-30 004149](https://user-images.githubusercontent.com/80672452/204578564-23b98c04-4606-4722-b451-8fdd3b6641eb.png)

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
  - 特にないです

2022-11-30 04:35 UTC, yuuki-foll requested changes
対応お願いします。

2022-11-30 04:35 UTC, yuuki-foll commented on src/resources/views/main_page.blade.php
> +                    <a href="{{route('fileList')}}" class="inline-block w-52 text-xl text-white bg-gray-800 px-7 hover:bg-gray-700 rounded-xl">ファイル一覧表示</a>
[imo]
windowsとmacのデフォルトのフォントの違いによるためだと思われますが、macで表示した際に、「ファイル一覧表示」が2行になってしまうので、フォントを設定してみてください。

2022-11-30 13:35 UTC, yuji-matsunami commented on src/resources/views/main_page.blade.php
> +                    <a href="{{route('fileList')}}" class="inline-block w-52 text-xl text-white bg-gray-800 px-7 hover:bg-gray-700 rounded-xl">ファイル一覧表示</a>
ありがとうございます！
いったんこれにしてみます
https://fonts.google.com/noto/specimen/Noto+Sans+JP
また話し合いましょう！

2022-11-30 14:55 UTC, yuji-matsunami commented on src/resources/views/main_page.blade.php
> +                    <a href="{{route('fileList')}}" class="inline-block w-52 text-xl text-white bg-gray-800 px-7 hover:bg-gray-700 rounded-xl">ファイル一覧表示</a>
@yuuki-foll 
こちらで修正しました。
[fix: windows, macのフォントの違いからスタイルがずれていたのを修正](https://github.com/yuuki-foll/Pylon/pull/24/commits/7d7c701947f32d3c937d04a42552a97045b007ad)
確認お願いします。

2022-12-01 10:51 UTC, yuuki-foll commented on src/resources/views/main_page.blade.php
> +                    <a href="{{route('fileList')}}" class="inline-block w-52 text-xl text-white bg-gray-800 px-7 hover:bg-gray-700 rounded-xl">ファイル一覧表示</a>
修正確認しました！
<img src="https://images.lgtmgen.org/da704f7e-3c41-4830-9d8b-0a4f342994cc" alt="LGTM" />

2022-12-01 10:52 UTC, yuuki-foll approved these changes

2022-12-01 10:53 UTC, yuuki-foll commented
またLGTM出す場所間違えたわ…

2022-12-01 10:56 UTC, yuji-matsunami commented
> またLGTM出す場所間違えたわ…

どんまい

2022-12-01 13:10 UTC, merged