Feature/page css
yuuki-foll/Pylon pull request #25
Opened 2022-11-30 04:42 UTC by yuuki-foll

## やったこと

* 簡易的なファイル一覧ページのUI作成
* 簡易的なファイル作成ページのUI作成

## やらないこと

* このプルリクでやらないことは何か？（あれば。無いなら「無し」でOK）（やらない場合は、いつやるのかを明記する。）
* 無し

## 動作確認

* どのような動作確認を行ったのか？　結果はどうか？
↓ファイル一覧ページ
<img width="1424" alt="スクリーンショット 2022-11-29 23 46 11" src="https://user-images.githubusercontent.com/80634409/204708747-72c6ac6d-19cb-461a-b5ce-2c1084349e55.png">

↓ファイル作成ページ
<img width="864" alt="スクリーンショット 2022-11-30 13 40 58" src="https://user-images.githubusercontent.com/80634409/204709147-540a8c5e-0905-4998-9b7c-36c28361882e.png">

## その他

* レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
* 特に無し

2022-11-30 14:38 UTC, yuji-matsunami reviewed
デザインはgoodだと思います！
ファイル変更せずに返答だけでもよいです。返答次第でApproveでも良いかと思います。

2022-11-30 14:38 UTC, yuji-matsunami commented on src/resources/views/makefile.blade.php
> +        <textarea name=”text” style="width:100%; height:60vh;" class="whitespace-pre-wrap"></textarea>
ここ多分最終的に<textarea>ではなくなりますよねー。
ここらへんの実装はちょっと話し合い、調査が必要そうですね。
(今回はここままでOKとします)

2022-11-30 14:38 UTC, yuji-matsunami commented on src/resources/views/filedata.blade.php
> +        <th>{{ $filedata->file_name }}</th>
[q]
ファイル名は中央揃えにした理由がしりたいです。
個人的には左詰めの方が見やすいかなと思いました。

2022-11-30 14:38 UTC, yuji-matsunami commented on src/resources/views/filedata.blade.php
> +        <th>更新日時</th>
[imo]
最終更新者とかも表示できたら良いですね。
取り敢えずオーナの箇所みたいな対応だけでもできたら良いです(ロジックは後回しでも)

2022-11-30 14:38 UTC, yuji-matsunami commented on src/resources/views/filedata.blade.php
> +        <th>更新日時</th>
ファイル名や日時でsortできたらよさそう
これもボタンだけ追加でロジックは後回しにしても可です

2022-11-30 14:38 UTC, yuji-matsunami commented on src/resources/views/filedata.blade.php
> +  <x-slot name="header"></x-slot>
{{$header}}なくてよさそうですね
templateから消します？
他のファイルを見てみると、空の<x-slot>がなかったので、最初の設計がまずかったかもです・・・

2022-12-01 10:18 UTC, yuuki-foll commented on src/resources/views/filedata.blade.php
> +        <th>{{ $filedata->file_name }}</th>
特に理由はないです。
確かに左詰めの方が見やすいと思うので修正します。

2022-12-01 10:18 UTC, yuuki-foll commented on src/resources/views/filedata.blade.php
> +        <th>更新日時</th>
了解です。
形だけ作っておきます。

2022-12-01 10:19 UTC, yuuki-foll commented on src/resources/views/makefile.blade.php
> +        <textarea name=”text” style="width:100%; height:60vh;" class="whitespace-pre-wrap"></textarea>
そうですね。
また話し合いお願いします。

2022-12-01 10:32 UTC, yuuki-foll commented on src/resources/views/filedata.blade.php
> +  <x-slot name="header"></x-slot>
確かに現時点では共通のヘッダしか使用してないので必要なさそうですね。
一回消しておいて個別に追加することがありそうなら復活させますか。

2022-12-01 10:54 UTC, yuji-matsunami commented on src/resources/views/filedata.blade.php
> +  <x-slot name="header"></x-slot>
これについては別ブランチでやりますね

2022-12-01 10:55 UTC, yuuki-foll commented on src/resources/views/filedata.blade.php
> +  <x-slot name="header"></x-slot>
了解です！

2022-12-02 14:14 UTC, yuji-matsunami requested changes
コメントしました。

2022-12-15 05:35 UTC, yuuki-foll commented on src/resources/views/filedata.blade.php
> +        <th align="left">ファイル名</th>
前の10～15文字程度だけ表示するように変更します。
カーソルあわせたら全部見えるとかはまた今度で

2022-12-15 15:02 UTC, yuji-matsunami approved these changes
![LGTM](https://image.lgtmoon.dev/191285)

2022-12-17 09:01 UTC, merged