ファイル内容の更新機能の追加
yuuki-foll/Pylon pull request #33
Opened 2022-12-24 16:13 UTC by yuuki-foll

## やったこと

* ファイル内容を更新できるように変更

## やらないこと

* 無し

## 動作確認

* 実際にファイル名・内容を変更して反映されたのを確認

## その他

* コードの書き方に自信がないのでもっと良い書き方があればコメントお願いします。

2022-12-24 17:26 UTC, yuji-matsunami requested changes
ちょっとだけ手直ししてほしいです。

2022-12-24 17:26 UTC, yuji-matsunami commented on src/app/Http/Controllers/FiledataController.php
> +        }
ここ非常によくないです。
- まず$isUserIdはstring型の変数"1"とか"2"なのでif("1")というやばいことやってます。
  - クエリにしていされてない時$isUserIdがnullになるので`isset()`使うとかかなと思います。
- いまのままだと他人のファイルにアクセスできます。
  - URLのidを適当にいじってもファイルが見れちゃう
- whereでint型のカラムをstringで比較してますね。データベースが良しなに型変換してくれるのですがアンチパターンかなと思います。 [参考](https://kojimanotech.com/2021/01/31/285/)

2022-12-24 17:26 UTC, yuji-matsunami commented on src/app/Http/Controllers/FiledataController.php
> +            $isId = $request->file_id;
$isIdはおかしいですね

2022-12-24 17:26 UTC, yuji-matsunami commented on src/app/Http/Controllers/FiledataController.php
> +            $data->save();
[q]
updateではなくsave()にした理由ってありますか？

2022-12-24 17:44 UTC, yuuki-foll commented on src/resources/views/filedata.blade.php
> +        <td><a href="{{ route('makeFile',['user_id'=>$filedata->user_id,'id'=>$filedata->id]) }}">{{ Str::limit($filedata->file_name,10) }}</a></td>
なるほど。確かにカーソルを合わせた時に何か変化があった方が良さそうですね。
試してみます。

2022-12-24 17:45 UTC, yuuki-foll commented on src/app/Http/Controllers/FiledataController.php
> +        $isId = $request->input('id');
確かに。修正します。

2022-12-25 15:22 UTC, yuuki-foll commented on src/app/Http/Controllers/FiledataController.php
> +            $data->save();
他の書き方を知らなかったです。変更した方が良いのであればまた修正します。

2022-12-25 15:24 UTC, yuuki-foll commented on src/app/Http/Controllers/FiledataController.php
> +            $isId = $request->file_id;
`$id`に修正しました。

2022-12-25 16:16 UTC, yuji-matsunami approved these changes
![LGTM](https://images.lgtmgen.org/4a34d84c-cff0-4952-a4f6-307f79c6e183)

2022-12-25 16:18 UTC, merged